steps:
  #retrieve key
  - name: 'gcr.io/cloud-builders/gcloud'
    id: retrieve-read-key
    entrypoint: 'bash'
    dir: .  
    args:
    - '-c'
    - |
      gcloud secrets versions access ${_KEY_VERSION} --secret="grc-builder" --project=${_KEY_PROJECT}  > /root/.ssh/id_rsa;
    volumes:
    - name: 'ssh'
      path: /root/.ssh
  
  - name: 'gcr.io/cloud-builders/git'
    id: add-github-key
    entrypoint: 'bash'
    dir: .
    args:
    - '-c'
    - |
      chmod 600 /root/.ssh/id_rsa
      cat <<EOF >/root/.ssh/config
      Hostname github.com
      IdentityFile /root/.ssh/id_rsa
      EOF
      ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    volumes:
    - name: 'ssh'
      path: /root/.ssh

  - id: 'generate-diffs'
    name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args: [
      './cloudbuild/scripts/get_diffs.sh
    volumes:
      - name: 'ssh'
        path: /root/.ssh
    env: [
      'BASE_REPO_URL=git@github.com:terekete/gcr_builder_test.git',
      'BASE_BRANCH=${_BASE_BRANCH}',
      'PR_NUMBER=${_PR_NUMBER}',
    ]
  
#   - id: 'build-images'
#     name: 'gcr.io/cloud-builders/docker'
#     entrypoint: bash
#     args: [
#       './cloud-build/scripts/build-images.sh'
#     ]
#     volumes:
#       - name: 'ssh'
#         path: /root/.ssh
#     env: [
#       'CONTAINER_IMAGE_REGISTRY=${_CONTAINER_IMAGE_REGISTRY}',
#     ]

#   - id: 'save-diff' 
#     name: gcr.io/cloud-builders/gcloud
#     entrypoint: 'bash'
#     args:
#       - -c
#       - |
#         echo "Saving diff file to ${_DIFF_BUCKET}"
#         commit=$(cat commit.txt)
#         gsutil cp "DIFF_IMAGES.txt" "gs://${_DIFF_BUCKET}/${commit}.txt"

# tags: ['build-release-candidate-images', "pull-${_PR_NUMBER}"]

options:
  substitution_option: 'ALLOW_LOOSE'

substitutions:
  _KEY_PROJECT: bi-stg-pineapple-345822
  _KEY_VERSION: latest
  _DIFF_BUCKET: 
  _CONTAINER_IMAGE_REGISTRY: 
  _BASE_BRANCH: 

timeout: 10800s
