steps:
  #retrieve key
  - name: 'gcr.io/cloud-builders/gcloud'
    id: retrieve-read-key
    entrypoint: 'bash'
    dir: .  
    args:
    - '-c'
    - |
      gcloud secrets versions access ${_KEY_VERSION} --secret="gcr-builder" --project=${_KEY_PROJECT}  > /root/.ssh/id_rsa;
    volumes:
    - name: 'ssh'
      path: /root/.ssh
  
  - name: 'gcr.io/cloud-builders/git'
    id: add-github-key
    entrypoint: 'bash'
    dir: .
    args:
    - '-c'
    - |
      chmod 600 /root/.ssh/id_rsa
      cat <<EOF >/root/.ssh/config
      Hostname github.com
      IdentityFile /root/.ssh/id_rsa
      EOF
      ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    volumes:
    - name: 'ssh'
      path: /root/.ssh

options:
  substitution_option: 'ALLOW_LOOSE'

substitutions:
  _KEY_PROJECT: bi-stg-pineapple-345822
  _KEY_VERSION: latest
  _DIFF_BUCKET: 
  _CONTAINER_IMAGE_REGISTRY: 
  _BASE_BRANCH: 

timeout: 10800s